spring:
  application:
    name: messages

server:
  port: 8080
eureka:
  instance:
    host-name: ${MESSAGES_HOSTNAME}
    non-secure-port: 80
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME}:8761/eureka

redis:
  host: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}