spring:
  application:
    name: messages

server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${MESSAGES_IP}
    non-secure-port: 80
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE}/eureka

redis:
  host: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}