spring:
  application:
    name: messages

server:
  port: ${MESSAGES_PORT}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME}:8761/eureka

redis:
  host: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}
---
spring:
  config:
    activate:
      on-profile: aws
eureka:
  instance:
    host-name: ${MESSAGES_HOSTNAME}
    ip-address: ${MESSAGES_IP}
---
spring:
  config:
    activate:
      on-profile: docker-compose