spring:
  application:
    name: messages

server:
  port: ${MESSAGES_PORT}

redis:
  host: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}

allowedOrigins: ${ALLOWED_ORIGINS}