spring:
  application:
    name: messages

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE}/eureka

redis:
  host: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}