services:
  messages:
    image: messages:latest
    container_name: messages
    hostname: messages
    networks:
      - net
    ports:
      - "8081:8080"
    env_file: messages/.env
    restart: always
  redis:
    image: redis:7.4.1
    container_name: redis
    hostname: redis
    networks:
      - net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/users.acl:/etc/redis/users.acl
    command: redis-server /etc/redis/redis.conf
    restart: always

  discovery:
    image: discovery:latest
    container_name: discovery
    hostname: discovery
    networks:
      - net
    ports:
      - "8761:8761"
    restart: always
  gateway:
    image: gateway:latest
    container_name: gateway
    hostname: gateway
    networks:
      - net
    ports:
      - "8080:8080"
    env_file: gateway/.env
    restart: always

volumes:
  redis-data:

networks:
  net:
