services:
  redis:
    image: redis:7.4.1
    container_name: redis-1
    hostname: redis-1
    networks:
      - net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:

networks:
  net:
