services:
  messages:
    image: messages:latest
    container_name: messages-1
    hostname: messages-1
    networks:
      - net
    ports:
      - "8081:8080"
    env_file: messages/.env
  redis:
    image: redis:7.4.1
    container_name: redis-1
    hostname: redis-1
    networks:
      - net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf
      - ./users.acl:/etc/redis/users.acl
    command: redis-server /etc/redis/redis.conf

volumes:
  redis-data:

networks:
  net:
