spring:
  application:
    name: gateway
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVICE}/eureka
client:
  messages:
    eurekaServiceId: ${MESSAGES_SERVICE_ID}