spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${ALLOWED_ORIGINS}
            allowedMethods:
              - GET
              - POST
            allowedHeaders: "*"
            exposedHeaders: "*"
            maxAge: 3600
      routes:
        - id: push-message
          uri: lb://${client.messages.eurekaServiceId}
          predicates:
            - Path=/messages
            - Method=POST
        - id: get-messages
          uri: lb://${client.messages.eurekaServiceId}
          predicates:
            - Path=/messages
            - Method=GET

server:
  port: ${GATEWAY_PORT}
client:
  messages:
    eurekaServiceId: ${MESSAGES_SERVICE_ID}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOSTNAME}:8761/eureka
---
spring:
  config:
    activate:
      on-profile: aws
eureka:
  instance:
    host-name: ${GATEWAY_HOSTNAME}
    ip-address: ${GATEWAY_IP}
---
spring:
  config:
    activate:
      on-profile: docker-compose